'''
Required: results_{cassandra,mongo,mysql}.json that are generated by main.py

This script will plot the mean time deltas of each DB benchmark
'''

import json
import pandas as pd
import matplotlib.pyplot as plt
from itertools import permutations

def format_dict(data):
    d = {'mean': {}}
    for b in data:
        if data[b]['success'] is False:
            continue
        d['mean'][b] = data[b]['time']['mean']
    return pd.DataFrame(d)

def plot_difference(d1, d2, colname, title, fname):
    try:
        df = d1 - d2
        df.rename(columns={'mean': colname}, inplace=True)
        ax = df.plot.bar()
        ax.set_xlabel('Benchmark')
        ax.set_ylabel('Time (ms)')
        ax.set_title(title)
        plt.savefig(fname, bbox_inches='tight')
        print(f'Saved {fname}')
    except Exception as e:
        print(f'Failed to plot {fname}')
        print(e)

with open('results_mongo.json') as f:
    mongo_data = json.load(f)
with open('results_mysql.json') as f:
    mysql_data = json.load(f)
with open('results_cassandra.json') as f:
    cass_data = json.load(f)

dbs = ['mongo','mysql','cassandra']
langs = ['java', 'python']
dfs = {}
for lang in langs:
    for db, data in zip(dbs, [mongo_data, mysql_data, cass_data]):
        if db not in dfs:
            dfs[db] = {}
        dfs[db][lang] = format_dict(data[lang])

for db in dbs:
    plot_difference(
        dfs[db]['python'],
        dfs[db]['java'],
        'Python-Java',
        f'{db.capitalize()} Python, Java Difference',
        f'{db.capitalize()}_python_java_difference.png',
    )

# for db1, db2 in permutations(dbs, 2):
#     for lang in langs:
#         plot_difference(
            
#         )
